spring.application.name=wolf-calie

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/wolf_calie?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret-key=25287f3e498c484a9e52c8a77a941ab5a78229b015e12f682d3ea8cd30f6b7c5
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000
